[package]
name = "replog"
version = "0.1.0"
edition = "2024"
description = "A Kafka-style replicated commit log, built from scratch"
license = "MIT"

[dependencies]
crc32fast = "1"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "time", "macros", "process"] }
rdkafka = { version = "0.39", features = ["cmake-build", "tokio"], optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"

[features]
kafka = ["rdkafka"]

[dev-dependencies]
tempfile = "3"
